# Generated by Django 6.0.4 on 2026-05-14 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='class_type',
            field=models.CharField(choices=[('LECTURE', 'Lecture'), ('ONLINE', 'Online')], default='LECTURE', max_length=10),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.room'),
        ),
    ]
