# Generated by Django 6.0.4 on 2026-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_student_classschedule_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='section',
            field=models.CharField(choices=[('IT3R1', 'IT3R1'), ('IT3R2', 'IT3R2'), ('IT3R3', 'IT3R3'), ('IT3R4', 'IT3R4'), ('IT3R5', 'IT3R5'), ('IT3R6', 'IT3R6'), ('IT3R7', 'IT3R7'), ('IT3R8', 'IT3R8'), ('IT3R9', 'IT3R9'), ('IT3R10', 'IT3R10')], default='IT3R1', max_length=10),
        ),
    ]
