# Generated by Django 6.0.4 on 2026-05-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_classschedule_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('students', models.ManyToManyField(blank=True, related_name='sections', to='scheduling.student')),
            ],
        ),
    ]
